### ISSUE TITLE
Add wkdev-setup-debugging host script

### ISSUE THREAD

**Issue by TingPing** [Igalia/webkit-container-sdk#24]
```
patrick@wkdev:~/checkout/WebKit$ rr record echo 'hello world'
rr needs /proc/sys/kernel/perf_event_paranoid <= 1, but it is 2.
Change it to 1, or use 'rr record -n' (slow).
Consider putting 'kernel.perf_event_paranoid = 1' in /etc/sysctl.d/10-rr.conf.
See 'man 8 sysctl', 'man 5 sysctl.d' (systemd systems)
and 'man 5 sysctl.conf' (non-systemd systems) for more details.
```

**Comment by nikolaszimmermann** [comment]
I'm not sure anymore if we really need this. `rr` is actually nice and explains what you need to do on your host system.
How about we just add a README.md section for tools like rr/perf/etc. and describe with a few sentences what needs to be done on the host -- there are so many host distros, that handle things differently, probably hard to script it.

**Comment by fred-wang** [comment]
FWIW, this is https://github.com/rr-debugger/rr/wiki/Building-And-Installing#os-configuration

**Comment by mbrodesser-Igalia** [comment]
> I'm not sure anymore if we really need this. `rr` is actually nice and explains what you need to do on your host system. How about we just add a README.md section for tools like rr/perf/etc. and describe with a few sentences what needs to be done on the host -- there are so many host distros, that handle things differently, probably hard to script it.

Running WebKitGTK's MiniBrowser on the host system fails on Ubuntu 24.04; that is, without rr:
```
$ Tools/Scripts/run-minibrowser --gtk --debug
/home/mirko/work/code/WebKit/WebKitBuild/GTK/Debug/bin/MiniBrowser: error while loading shared libraries: libocdm.so: cannot open shared object file: No such file or directory

ScriptError raised: Failed to run "['/home/mirko/work/code/WebKit/WebKitBuild/GTK/Debug/bin/MiniBrowser']" exit_code: 127 cwd: /home/mirko/work/code/WebKit
Traceback (most recent call last):
  File "/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/minibrowser/run_webkit_app.py", line 65, in main
    return port.run_minibrowser(browser_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/port/gtk.py", line 188, in run_minibrowser
    return self._executive.run_command(command + args, cwd=self.webkit_base(), stdout=None, return_stderr=False, decode_output=False, env=env, pass_fds=pass_fds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/common/system/executive.py", line 425, in run_command
    (error_handler or self.default_error_handler)(script_error)
  File "/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/common/system/abstractexecutive.py", line 98, in default_error_handler
    raise error
webkitpy.common.system.executive.ScriptError: Failed to run "['/home/mirko/work/code/WebKit/WebKitBuild/GTK/Debug/bin/MiniBrowser']" exit_code: 127 cwd: /home/mirko/work/code/WebKit
```

so it'd be convenient if rr in a webkit-container-sdk works without further configuration steps.

**Comment by mbrodesser-Igalia** [comment]
```
$ rr record echo 'hello world'
rr: Saving execution to trace directory `/home/mirko/.local/share/rr/echo-1'.
hello world
```
works after installing `linux-tools-6.8.0-52-generic` and `linux-cloud-tools-6.8.0-52-generic` and re-entering the container.

Installing the packages was suggested by
```
 perf stat -e r5111c4 true
WARNING: perf not found for kernel 6.8.0-52

  You may need to install the following packages for this specific kernel:
    linux-tools-6.8.0-52-generic
    linux-cloud-tools-6.8.0-52-generic

  You may also want to install one of the following packages to keep up to date:
    linux-tools-generic
    linux-cloud-tools-generic
```

**Comment by mbrodesser-Igalia** [comment]
> FWIW, this is https://github.com/rr-debugger/rr/wiki/Building-And-Installing#os-configuration

That fixes
```
$ rr record --bind-to-cpu=0 echo 'hello world'
rr: Saving execution to trace directory `/home/mirko/.local/share/rr/echo-8'.
hello world
```

`--bind-to-cpu=0` was required because of https://github.com/rr-debugger/rr/issues/3338#issue-1316036257.

Recording a WebKitGTK MiniBrowser run fails:
```
$ WEBKIT_MINI_BROWSER_PREFIX="rr record --bind-to-cpu=0" Tools/Scripts/run-minibrowser --gtk --debug
rr: Saving execution to trace directory `/home/mirko/.local/share/rr/MiniBrowser-10'.
bwrap: Can't create tmpfile for /.flatpak-info: File exists

** (MiniBrowser:20465): ERROR **: 15:55:51.179: Failed to fully launch dbus-proxy: Child process exited with code 1

ScriptError raised: Failed to run "['rr', 'record', '--bind-to-cpu=0', '/host/home/mirko/work/code/WebKit/WebKitBuild/GTK/Debug/bin/MiniBrowser']" exit_code: -5 cwd: /host/home/mirko/work/code/WebKit
Traceback (most recent call last):
  File "/host/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/minibrowser/run_webkit_app.py", line 65, in main
    return port.run_minibrowser(browser_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/host/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/port/gtk.py", line 188, in run_minibrowser
    return self._executive.run_command(command + args, cwd=self.webkit_base(), stdout=None, return_stderr=False, decode_output=False, env=env, pass_fds=pass_fds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/host/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/common/system/executive.py", line 425, in run_command
    (error_handler or self.default_error_handler)(script_error)
  File "/host/home/mirko/work/code/WebKit/Tools/Scripts/webkitpy/common/system/abstractexecutive.py", line 98, in default_error_handler
    raise error
webkitpy.common.system.executive.ScriptError: Failed to run "['rr', 'record', '--bind-to-cpu=0', '/host/home/mirko/work/code/WebKit/WebKitBuild/GTK/Debug/bin/MiniBrowser']" exit_code: -5 cwd: /host/home/mirko/work/code/WebKit
```
